### ISSUE TITLE
some issues 

### ISSUE THREAD

**Issue by mubdea** [payfort/magento#7]
1. The app does not automatically generate invoice when payment is successfully completed. It should automatically generate invoice.

2. The app is not store view compatible. Which is not good for multi-language stores

**Comment by alovak** [comment]
@mubdea do you know why it so and how to fix it?

I would appreciate any help

**Comment by mubdea** [comment]
I am really sorry, I know nothing about programming, I just faced these issues and wanted to share it with you it can be fixed in future updates.

sorry if this is not the right place for sharing issues
